In [1]:
#01-08-2023

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
amazon = pd.read_csv(r"G:\Imarticus Learning\Python - Pranjal\NLP\AmazonFoodReviews.csv")

In [3]:
amazon.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [4]:
amazon.shape

(568454, 10)

In [5]:
amazon.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [6]:
amazon.drop(['Id', 'ProductId', 'UserId','ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator','Time','Summary'], axis = 1)

Score                                               Text
0           5  I have bought several of the Vitality canned d...
1           1  Product arrived labeled as Jumbo Salted Peanut...
2           4  This is a confection that has been around a fe...
3           2  If you are looking for the secret ingredient i...
4           5  Great taffy at a great price.  There was a wid...
...       ...                                                ...
568449      5  Great for sesame chicken..this is a good if no...
568450      2  I'm disappointed with the flavor. The chocolat...
568451      5  These stars are small, so you can give 10-15 o...
568452      5  These are the BEST treats for training and rew...
568453      5  I am very satisfied ,product is as advertised,...

[568454 rows x 2 columns]

In [7]:
amazon.Score.value_counts()

5    363122
4     80655
1     52268
3     42640
2     29769
Name: Score, dtype: int64

In [8]:
amazon.replace({2:1,3:2,4:3,5:3}, inplace = True)

In [9]:
amazon.Score.value_counts()

3    443777
1     82037
2     42640
Name: Score, dtype: int64

In [10]:
amazon.Text = amazon.Text.str.lower()

In [11]:
from nltk.corpus import stopwords

In [12]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [13]:
import string

In [14]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [15]:
stopword_list = list(stopwords.words("english"))

In [16]:
def text_process(mess):            ### creating a function
    """                                                        ## a docstring
    1. remove the punctuation
    2. remove the stopwords
    3. return the list of clean textwords
    
    """
    nopunc = [char for char in mess if char not in string.punctuation]
    nopunc = "".join(nopunc)
    
    return [ word for word in nopunc.split() if word not in stopword_list]

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
#CountVect is used to counts for each word

In [18]:
amazon_transformer = CountVectorizer(analyzer=text_process).fit(amazon.Text)

In [19]:
amazon_transformer.vocabulary_

{'bought': 35857,
 'several': 191850,
 'vitality': 229827,
 'canned': 42395,
 'dog': 69985,
 'food': 87189,
 'products': 172594,
 'found': 88450,
 'good': 95108,
 'quality': 175518,
 'product': 172343,
 'looks': 132324,
 'like': 130309,
 'stew': 204098,
 'processed': 172170,
 'meat': 137919,
 'smells': 196972,
 'better': 31728,
 'labrador': 127070,
 'finicky': 84290,
 'appreciates': 23175,
 'arrived': 24124,
 'labeled': 126924,
 'jumbo': 123471,
 'salted': 186534,
 'peanutsthe': 162728,
 'peanuts': 162695,
 'actually': 15812,
 'small': 196667,
 'sized': 195465,
 'unsalted': 225858,
 'sure': 208961,
 'error': 77454,
 'vendor': 228603,
 'intended': 119211,
 'represent': 181173,
 'confection': 55158,
 'around': 24006,
 'centuries': 45428,
 'light': 130088,
 'pillowy': 165773,
 'citrus': 50548,
 'gelatin': 92424,
 'nuts': 152690,
 'case': 44135,
 'filberts': 83761,
 'cut': 61676,
 'tiny': 218077,
 'squares': 202312,
 'liberally': 129676,
 'coated': 51763,
 'powdered': 169667,
 'sugar': 207

In [20]:
len(amazon_transformer.vocabulary_)

240626

In [21]:
tdm = amazon_transformer.transform(amazon.Text)

In [22]:
tdm.shape

(568454, 240626)

In [23]:
type(tdm)

scipy.sparse._csr.csr_matrix

In [24]:
#Sampling

In [25]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(tdm, amazon.Score, test_size=.2)

In [26]:
x_train.shape

(454763, 240626)

In [27]:
y_train.shape

(454763,)

In [ ]:
#Model Building

In [29]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

In [30]:
nb.fit(x_train, y_train)

MultinomialNB()

In [31]:
pred = nb.predict(x_test)

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [33]:
confusion_matrix(y_test, pred)

array([[10662,   985,  4622],
       [ 1674,  2234,  4657],
       [ 3256,  2049, 83552]], dtype=int64)

In [55]:
tab = confusion_matrix(y_test, pred)

In [34]:
accuracy_score(y_test, pred)

0.8483345207624174

In [ ]:
#Decision Tree

In [35]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

In [37]:
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [38]:
pred_dt = dt.predict(x_test)

In [40]:
confusion_matrix(y_test, pred_dt)

array([[10748,   939,  4582],
       [ 1159,  4079,  3327],
       [ 3754,  2256, 82847]], dtype=int64)

In [41]:
accuracy_score(y_test, pred_dt)

0.8591181360002111

In [42]:
#Random Forest

In [43]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [44]:
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [45]:
pred_rfc = rfc.predict(x_test)

In [110]:
confusion_matrix(y_test, pred_rfc)

array([[ 8439,    10,  8033],
       [  154,  3313,  5002],
       [   70,    11, 88659]], dtype=int64)

In [111]:
accuracy_score(y_test, pred_rfc)*100

88.31921612088908

In [48]:
#Logistic Regression

In [49]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [50]:
log.fit(x_train, y_train)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [51]:
pred_log = log.predict(x_test)

In [52]:
confusion_matrix(y_test, pred_log)

array([[11703,   855,  3711],
       [ 1646,  2756,  4163],
       [ 1988,  1323, 85546]], dtype=int64)

In [53]:
accuracy_score(y_test, pred_log)

0.8796210781856083

In [56]:
tab = pd.DataFrame(tab)
tab.columns = ['Bad', 'Avg', 'Best']
tab.index = ['Bad', 'Avg', 'Best']
tab

Bad   Avg   Best
Bad   10662   985   4622
Avg    1674  2234   4657
Best   3256  2049  83552

In [ ]:
#SVM

In [29]:
from sklearn.svm import SVC

svm = SVC()

In [ ]:
svm.fit(x_train, y_train)

In [ ]:
#Lets try same dataset with 'Summary'

In [57]:
amz = pd.read_csv(r"G:\Imarticus Learning\Python - Pranjal\NLP\AmazonFoodReviews.csv")

In [58]:
amz.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [59]:
amz.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [60]:
amazon.drop(['Id', 'ProductId', 'UserId','ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator','Time','Text'], axis = 1)

Score                             Summary
0           3               Good Quality Dog Food
1           1                   Not as Advertised
2           3               "Delight" says it all
3           1                      Cough Medicine
4           3                         Great taffy
...       ...                                 ...
568449      3                 Will not do without
568450      1                        disappointed
568451      3            Perfect for our maltipoo
568452      3  Favorite Training and reward treat
568453      3                         Great Honey

[568454 rows x 2 columns]

In [61]:
amz.replace({2:1,3:2,4:3,5:3}, inplace = True)

In [62]:
amz.Score.value_counts()

3    443777
1     82037
2     42640
Name: Score, dtype: int64

In [63]:
amz.Text = amz.Text.str.lower()

In [64]:
from nltk.corpus import stopwords

In [65]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [66]:
import string

In [67]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [68]:
stopword_list = list(stopwords.words("english"))

In [69]:
def text_process(mess):            ### creating a function
    """                                                        ## a docstring
    1. remove the punctuation
    2. remove the stopwords
    3. return the list of clean textwords
    
    """
    nopunc = [char for char in mess if char not in string.punctuation]
    nopunc = "".join(nopunc)
    
    return [ word for word in nopunc.split() if word not in stopword_list]

In [70]:
from sklearn.feature_extraction.text import CountVectorizer
#CountVect is used to counts for each word

In [71]:
amz_transformer = CountVectorizer(analyzer=text_process).fit(amz.Text)

In [74]:
amz_transformer.vocabulary_

{'bought': 35857,
 'several': 191850,
 'vitality': 229827,
 'canned': 42395,
 'dog': 69985,
 'food': 87189,
 'products': 172594,
 'found': 88450,
 'good': 95108,
 'quality': 175518,
 'product': 172343,
 'looks': 132324,
 'like': 130309,
 'stew': 204098,
 'processed': 172170,
 'meat': 137919,
 'smells': 196972,
 'better': 31728,
 'labrador': 127070,
 'finicky': 84290,
 'appreciates': 23175,
 'arrived': 24124,
 'labeled': 126924,
 'jumbo': 123471,
 'salted': 186534,
 'peanutsthe': 162728,
 'peanuts': 162695,
 'actually': 15812,
 'small': 196667,
 'sized': 195465,
 'unsalted': 225858,
 'sure': 208961,
 'error': 77454,
 'vendor': 228603,
 'intended': 119211,
 'represent': 181173,
 'confection': 55158,
 'around': 24006,
 'centuries': 45428,
 'light': 130088,
 'pillowy': 165773,
 'citrus': 50548,
 'gelatin': 92424,
 'nuts': 152690,
 'case': 44135,
 'filberts': 83761,
 'cut': 61676,
 'tiny': 218077,
 'squares': 202312,
 'liberally': 129676,
 'coated': 51763,
 'powdered': 169667,
 'sugar': 207

In [75]:
len(amz_transformer.vocabulary_)

240626

In [77]:
tdm = amz_transformer.transform(amz.Text)

In [78]:
tdm.shape

(568454, 240626)

In [79]:
type(tdm)

scipy.sparse._csr.csr_matrix

In [80]:
#Sampling

In [81]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(tdm, amz.Score, test_size=.2)

In [82]:
x_train.shape

(454763, 240626)

In [84]:
y_train.shape

(454763,)

In [ ]:
#Model_building

In [85]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

In [86]:
nb.fit(x_train, y_train)

MultinomialNB()

In [87]:
pred = nb.predict(x_test)

In [88]:
confusion_matrix(y_test, pred)

array([[10827,  1103,  4552],
       [ 1720,  2121,  4628],
       [ 3282,  2102, 83356]], dtype=int64)

In [89]:
accuracy_score(y_test, pred)

0.8470679297393813

In [ ]:
#Decision Tree

In [90]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

In [91]:
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [92]:
pred_dt = dt.predict(x_test)

In [93]:
confusion_matrix(y_test, pred_dt)

array([[11030,   903,  4549],
       [ 1230,  3960,  3279],
       [ 3526,  2251, 82963]], dtype=int64)

In [94]:
accuracy_score(y_test, pred_dt)

0.8615721561073436

In [ ]:
#Random Forest

In [95]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [96]:
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [97]:
pred_rfc = rfc.predict(x_test)

In [98]:
confusion_matrix(y_test, pred_dt)

array([[11030,   903,  4549],
       [ 1230,  3960,  3279],
       [ 3526,  2251, 82963]], dtype=int64)

In [99]:
accuracy_score(y_test, pred_dt)

0.8615721561073436

In [ ]:
#Logistic Regression

In [101]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [102]:
log.fit(x_train, y_train)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [104]:
pred_log = log.predict(x_test)

In [107]:
confusion_matrix(y_test, pred_log)

array([[11646,   797,  4039],
       [ 1638,  2581,  4250],
       [ 1896,  1251, 85593]], dtype=int64)

In [109]:
accuracy_score(y_test, pred_log)

0.8779938605518467

In [ ]:
#Results 

In [ ]:
#On Text

#Model showing good results on Random forest with around 88.31% accuracy but it is failing for class 1
#But Decision tree model shows good result on Text with 85.91% accurancy and perform well in every class

In [ ]:
#On Summary

#Model showing good results on Logistic Regression with around 87.79% accuracy but it is failing for class 1
#But Random Forest model shows good result on Text with 86.15% accurancy and perform well in every class

# LSTM

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras
from keras.models import Model, Sequential
from keras.layers import Embedding, Dense, LSTM, RNN

In [2]:
amz = pd.read_csv(r"G:\Imarticus Learning\Python - Pranjal\NLP\AmazonFoodReviews.csv")

In [3]:
amz.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [4]:
amz = amz.loc[:, ['Score', 'Text']]
amz.head()

Score                                               Text
0      5  I have bought several of the Vitality canned d...
1      1  Product arrived labeled as Jumbo Salted Peanut...
2      4  This is a confection that has been around a fe...
3      2  If you are looking for the secret ingredient i...
4      5  Great taffy at a great price.  There was a wid...

In [5]:
amz.Score.value_counts()

5    363122
4     80655
1     52268
3     42640
2     29769
Name: Score, dtype: int64

In [6]:
amz.Score.replace({1:0,2:0,3:1,4:2,5:2}, inplace = True)

In [7]:
amz.Score.value_counts()

2    443777
0     82037
1     42640
Name: Score, dtype: int64

In [8]:
amz_x = amz.iloc[:, 1]
amz_y = amz.iloc[:, 0]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(amz_x, amz_y, test_size=.2)

In [9]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((454763,), (113691,), (454763,), (113691,))

In [10]:
y_train.value_counts()

2    355094
0     65516
1     34153
Name: Score, dtype: int64

In [11]:
from keras.preprocessing.text import Tokenizer  #Assign number to each word
from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [12]:
y_train = to_categorical(y_train)

In [13]:
y_train

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [14]:
max_num_words  = 20000 #total how many words to be considered from the corpus(collection of documents)
seq_len        = 100   #how many words to be taken from each document
embedding_size = 200   #vector lengh (embedding size) for each word

In [15]:
tokenizer = Tokenizer(num_words = max_num_words)
tokenizer.fit_on_texts(amz.Text)
x_train = tokenizer.texts_to_sequences(x_train)
x_train = pad_sequences(x_train, maxlen = seq_len)

In [16]:
model = Sequential()  # iniitialize the network
model.add(Embedding( input_dim = max_num_words,    
                     input_length = seq_len,
                     output_dim = embedding_size))
model.add(LSTM(5))   #If we want to perform RNN then simply replace LSTM to RNN but recommended
model.add(Dense(3 , activation  = 'softmax'))   # final layer
from tensorflow.keras.optimizers import Adam
adam = Adam(lr = .001)
model.compile(optimizer= adam , loss = 'categorical_crossentropy' , metrics = ['accuracy'])

In [17]:
x_train.shape

(454763, 100)

In [18]:
y_train.shape

(454763, 3)

In [19]:
y_train

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [20]:
model.fit(x_train, y_train, epochs=4, batch_size = 128, validation_split=.2)

Epoch 1/4
2843/2843 [==============================] - 522s 182ms/step - loss: 0.4186 - accuracy: 0.8451 - val_loss: 0.3384 - val_accuracy: 0.8743
Epoch 2/4
2843/2843 [==============================] - 479s 168ms/step - loss: 0.2893 - accuracy: 0.8934 - val_loss: 0.3002 - val_accuracy: 0.8923
Epoch 3/4
2843/2843 [==============================] - 459s 161ms/step - loss: 0.2383 - accuracy: 0.9135 - val_loss: 0.2931 - val_accuracy: 0.8977
Epoch 4/4
2843/2843 [==============================] - 432s 152ms/step - loss: 0.2050 - accuracy: 0.9265 - val_loss: 0.2996 - val_accuracy: 0.8974


In [83]:
x_test = tokenizer.texts_to_sequences(x_test)
x_test = pad_sequences(x_test, maxlen=seq_len)

In [84]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [85]:
pred_prob = model.predict(x_test)

3553/3553 [==============================] - 67s 17ms/step


In [86]:
pred_classes = pred_prob.argmax(axis = 1)

In [87]:
tab1 = confusion_matrix(y_test, pred_classes)
tab1

array([[12771,  1060,  2806],
       [ 1466,  3357,  3650],
       [ 1527,  1032, 86022]], dtype=int64)

In [88]:
tab1.diagonal().sum()*100/tab1.sum()

89.84880069662506